# Generated by Django 5.1.6 on 2025-07-22 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SheetList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet_name', models.CharField(max_length=255, unique=True)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('event_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ParticipantId', models.CharField(max_length=255)),
                ('ParticipantName', models.CharField(max_length=255)),
                ('SessionAttended', models.CharField(default='A', max_length=5)),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='attendance_app.sheetlist')),
            ],
        ),
    ]
