# Generated by Django 5.1.6 on 2025-07-22 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='formList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_name', models.TextField()),
                ('form_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='userProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regno', models.CharField(max_length=9, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('hostel', models.CharField(max_length=5)),
                ('block', models.CharField(max_length=5)),
                ('room', models.CharField(max_length=5)),
                ('number', models.CharField(max_length=15, unique=True)),
                ('admin', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='formData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regno', models.CharField(max_length=9)),
                ('name', models.CharField(max_length=50)),
                ('domain', models.TextField()),
                ('NS', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='NS_form_key', to='user_app.formlist')),
            ],
        ),
    ]
