# Generated by Django 5.1.6 on 2025-03-24 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_rename_room_no_userprofile_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='formList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_name', models.TextField()),
                ('form_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='formdata',
            name='NS',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='NS_form_key', to='user_app.formlist'),
        ),
    ]
