# Generated by Django 5.1.6 on 2025-03-24 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_formlist_formdata_ns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formdata',
            name='regno',
            field=models.CharField(max_length=9),
        ),
    ]
